{% set version = '1.2-2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-goftest
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/goftest_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/goftest/goftest_{{ version }}.tar.gz
  sha256: e497992666b002b6c6bed73bf05047ad7aa69eb58898da0ad8f1f5b2219e7647

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('goftest')"           # [not win]
    - "\"%R%\" -e \"library('goftest')\""  # [win]
    - conda inspect linkages -p $PREFIX r-goftest  # [not win]
    - conda inspect objects -p $PREFIX r-goftest  # [osx]


about:
  home: https://github.com/baddstats/goftest
  license: GPL-2
  summary: Cramer-Von Mises and Anderson-Darling tests of goodness-of-fit for continuous univariate
    distributions, using efficient algorithms.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - jsignell

# Package: goftest
# Type: Package
# Title: Classical Goodness-of-Fit Tests for Univariate Distributions
# Version: 1.2-2
# Date: 2019-11-27
# Authors@R: c(person("Julian", "Faraway", role = "aut"), person("George", "Marsaglia", role = "aut"), person("John",   "Marsaglia", role = "aut"), person("Adrian", "Baddeley", role = c("aut", "cre"), email = "Adrian.Baddeley@curtin.edu.au"))
# Depends: R (>= 3.3)
# Imports: stats
# Description: Cramer-Von Mises and Anderson-Darling tests of goodness-of-fit for continuous univariate distributions, using efficient algorithms.
# URL: https://github.com/baddstats/goftest
# BugReports: https://github.com/baddstats/goftest/issues
# License: GPL (>= 2)
# NeedsCompilation: yes
# Packaged: 2019-11-27 01:56:07 UTC; adrian
# Author: Julian Faraway [aut], George Marsaglia [aut], John Marsaglia [aut], Adrian Baddeley [aut, cre]
# Maintainer: Adrian Baddeley <Adrian.Baddeley@curtin.edu.au>
# Repository: CRAN
# Date/Publication: 2019-12-02 11:20:02 UTC
