# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "RFZcNR8eQMRZ5hoyiHWEZpNyrkrWT/hErON6e/zYY19PNn5BFeP8JVCxgo68eWGnpKwXrZmV2XZ0vwCVvIAfOLe7AtOYagd1Aa4KS4MmaWQrnk2rLCO9SLLQh5ncXqViUW+ncZulU6E+1X5F8IgrYwMSl+xkINo0KibNNCWvcrSp+phDacwf2FME8MCsb9WTsibN0XIlQ+tjaEDtAqkisTBdfyzUKM7YohVX5H7chE+CbJO1stL1FFa57GbBvcAghJBC9fl5q//ud7H9blMByif2qSLCDr+WMPf1chW/ov4FZeNFQw2B7g8XEJa4D8ggKLEOpNx1nhpErA9iO8Ok72r1sSX7vT3jq6z2e/BiIJgSUsm9ee/TqbsQ4fOfikg/j801094uZB8PvfkTJWTRUhQ3XdKbJIb+17B15Pt+3MNHzYDy7B+my5kYf7OQKx4RNu2VElLcWUpkg8E0WPLC+mDm2hj/BURuwqmodDnj+y3XSV8Zfu85lZntEl+PQNhiNxQ3tUknqAA9L1DLGbb9j7wXenY9lVe2CwxA1DUTzEGDyt7dRxS6J0qjbhmPZpdMGs4TocYh+0RSqg8v7HrVK7WNhhtjllCeLXiCQJCa/yNrqnx+gddurkIPByl+rPN8hgyinHKtSoPRIyb+CNL9493JiyqqWsuGNr6wLFHm0xI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
