travis:
  secure:
    BINSTAR_TOKEN: viqVi1rLBg5PRtY/c75y11sPkFSWMLAc1lnnWIKUM9nDEl5UPjTbohjKlReZr16svLj3WyA6u++2L9CtIQ8JMt5dJIfZuhTAReQ0iJwhQVPMuWVwoNm+LkLwvEwtj/fdYyG604jU7Kdxcz04O4UiLcLc+MEF28Ol1OGmEmTv1Lh4xarXuhJJ+xCSljLfcxDvl0HuPulqyq8yHdaXp4d/sU/nnDd9poqo4MSTokTFlbm8TldukPQ0OfACvKHI7J1FaXYB4MmbAi5RCDYPhlWU1l5XIUYRB2akSH8i3i4A2eNY9qOMsH/tmLS05iA04LCm+7k4XdiBkK2vVYNHz1cB80y4DSttnsqKPm+tmmJwA2apMaQBHyc2DKMKRFWDIqD7RBCq+WvCTJgN02L8NzzbZyGFYnj4GIr671Yr2PGhkSmaSjGr1hRe6R7Nm6tL/UZt42BVTQYgobP69VEbjzXptkfByUc4UzNz5b7gdQp3qrrkz+NLSifMBSNFJKfx/g1c8pYmCaXirD1Nf3iDBd0oqZLutIJj51qQp5pdIo84MI2vMTE5c/NUteRhsVuiPRUxjR63nZt75K2EblhYcE3azIYWgDbHMmmedEw+5zfrlXgyPMXBp45fuuAh++m+egOCFR2SVA5OsUt3NrZuH5c6SaL1Qbg+XppJnng4brCyKoc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
