travis:
  secure:
    BINSTAR_TOKEN: qe2ZivsrPVLRKFTQx13E0GT/xwDOEQgSlzaPCC4MMWoQe/8GunMNHTYnOyRaud4UsPG6pZA6xNBMsPttB2wFX3Fy3uovdR9VBXBBSfW154SpXdZ2QNUF9PcPkhidajOtIxoKN9ZV/2r4luEOqxe7P9PBEoUsEO3UBck41gnonyJk15YVze+GycZii6DUp1alkUuVlXGPeCzCJqpS2OVm1XcYS46WVL7bLPCBFB1udeRCgu4pbG5aOARx5seotcLGyG5AJXHP0X0AzRVwWIAJeB9riNmZPeuvWuH2E7YR51+FZfK+IZuVJtnZqYkvNaPnMoBqBcByb0Y8c6dLfgJuSczQSowrQMCTwElZxBpLKUvRWeuE190Op/KGBzgdl1fwbgF7ItbcSdT2hhAoD3nKfpeRJsV+/ObvdIef2Y2EHCReGQfDmA3DCvx9GlC0fqIsg8VpDeMyPDwD4jt1PjIuNAn68UHOa5w46NkiWqXWO5XHBK+NSvJmolOvc8MkLveKOg6T4tQOzMi1qVXUR2uVxTJqq3hGfJhDwEYhCSNrzokanSsGfnEFFFXxaB2w1t5GXKwvPRIqpM0Ebz7vkzaAMj/61DBGAhMlYTHSGcQfVJZsXqjf80sPRGeKcx/4Ai46H3fjnU/33S5H47ptm5J2+vCgE7nhnwYd9gUZ7jMUIMI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
