travis:
  secure:
    BINSTAR_TOKEN: WL9sVqWxQJQP9GLbTNt8iiwTL6ukilGocpiIDqv/EOpxGorWtGuu1GyvQ0XvPb9yZBQkFbpFFphkRfydCmjmyHgdrRah/MzWq9iysxD/yKB8KHQMeB7VHlJ+pl5Bb/IgEKxsLY9W2zqnqR4o6AO9r2MBVadVPdWW1EEbjZG5G0Z/uy5kcgGNb+9D0SM974xCTsVRSm2hO2QT/uJIAIG8OjIbZUC/WRWw/eeco+Usebzk61u0y5gJFyWbQCY4v5YKdvuQmukFhM1HbrdDXWbh4+VxThZ7hNYWGEb8GQCqzewkwD4ac0UM9IHA5hHspgkQqOxz8RLHVAJs+C97xFKbpXCRSk5a5m3gNIDjj2koSdNodOC3i6X2hfcKKRyND/8yZ/kfFX0P3xKrk6CVRciy7KqCYyp2QQZg0rvHSRYbERwhdCqLG0sKXZA0eRRTenCueNIZhYYivQL2wi6HGbtgED/7NQ7YUIF5NcoH7rSxvcvg2QbjGyZ8J2kRW8QyBRsf8Y4UT9/AQf1C6cL3ttNdYENBsAUdr4hJXVz/uS5WdFocvhKvATj8ZFrJVanyhFJBWsK8D3TzaVsZQjHt5D1H8pvflB1WjamO6OqVXVHGeHHhamWdZVBUoAJkJ/GyYxb1TlNUQQ9GgWf5QCjfh1lyw49Tm+aQbHw3dX2yOozR6Wk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
