appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: 1Xpp7I99Uxaisdg2jCPUrjV0/wiZmgKjH9U7YyfXjWaklbE7GPAlFmK5+uG1fdnhEFLk8olOUEsGQTCTVkxBIBmCYBvMiWNcW7EchosDQcZeB2HDm5rWoMYzsSng0Zivy+Q5rZjki++PU/UplB1xylwwZ0y6HqVnAz11B8sW0uHgQt9PBdsGuSCHMZsY3niO2YNSCwCcGipqeGoP1mV39YVsXvvqEVMLzqphUNN1Yp/+WDs+DRgSwfQVSHUMfuPucpqCwZUhVnFDJdhzWYrtf9uztkt4yJmuzsRjGEQFRp/c/aVqsxFIKwGw6G4OtQccmFQ+ZZCIK9SZs4h86Qo/tqxzSAqG548xZqXuKSP55wgnPNiGZ/3C30rU6C4hWyA9cSImlEeZyPzLrHHDo8GNu0Y/06oeWQQTGdFt/cJi5bDflpGoFEm2Ogj6827o/ba3HMi7re7VUhERuTNI0chfabaeg1ECfaJ/jfL99p45U+XZfpgaumMrSDXYLjqww/vFhVWdDuHazrYJGjT9EGrmHp8hkHLmqJXUHwzSzzhAU1trbKL8WzEUJmiAywefuoc1MbMZPD5dAjo3UNU4cXuPtcoTv1MkMUJ3Qzm9eDax7nO8MFCbre9rQP7L4Mn4RaKP66hfy1bl9ZnpGo3fra12GavchgFhBHgV+2rGTKEx5ww=}
