travis:
  secure:
    BINSTAR_TOKEN: mSBm6KPWLM1AEI6Hl0W18SGTofwczwzjXbQJuAD58cYaoOqB9ARgrW6p60mTOZ6/TRDuOhTy9763LDAZ7skxtkgIwYvMxVR2mbVy5HaAlsSbW7iN2HjF2eKTqe+Lv2SvWYe8ears4kPHj3HN2BWm5MZAKlNuTkEOaP8BW5ZPZZI77rcCMEsVhT21HDjFnHPDnYhAAxA03b77c3JV9Er5cC52Kxj5ikjg5Du6Kgq4FpYwfd5b2p26HjRQKKjssiedo7G42Ul0zWNKaGkBHMFjO6AV9fdOfJ+Mih+21uXvkldzJy1cXnzoAuRB1GKptue06mbazbLDmEzWmtrwUMHej6MPvkO+KDCd5dmm9khlKRIL01lEkzceqGUKPmnLDMnC6QWt4XKzooXghEmAbzv+5TkKKrVuV5sfX8KHiNyLnsonMO0GjiFP0XUd57UrCo8yhr2WTf5TB1b/rsxIMxmI7WQBfnKM2M+hwb5HXHPOR3yqdsDxXvoJo+/cChrLOKZrlvwaI8CqngyY2Tnj+WLsMdELrz8Czhmt2XVbza8OcieOhTjrmixpsqFTaym7pqqUROEDtxFeCkaqh17e6KX9noSTb7u1mVQP9gps8QASLC9xQUn8IdBQCSVX1yKo6m1pyxQ4ftXdDHWASFdNUr7av0J3PGlaCJuZZ5fj0O7SQdQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
