travis:
  secure:
    BINSTAR_TOKEN: RFZcNR8eQMRZ5hoyiHWEZpNyrkrWT/hErON6e/zYY19PNn5BFeP8JVCxgo68eWGnpKwXrZmV2XZ0vwCVvIAfOLe7AtOYagd1Aa4KS4MmaWQrnk2rLCO9SLLQh5ncXqViUW+ncZulU6E+1X5F8IgrYwMSl+xkINo0KibNNCWvcrSp+phDacwf2FME8MCsb9WTsibN0XIlQ+tjaEDtAqkisTBdfyzUKM7YohVX5H7chE+CbJO1stL1FFa57GbBvcAghJBC9fl5q//ud7H9blMByif2qSLCDr+WMPf1chW/ov4FZeNFQw2B7g8XEJa4D8ggKLEOpNx1nhpErA9iO8Ok72r1sSX7vT3jq6z2e/BiIJgSUsm9ee/TqbsQ4fOfikg/j801094uZB8PvfkTJWTRUhQ3XdKbJIb+17B15Pt+3MNHzYDy7B+my5kYf7OQKx4RNu2VElLcWUpkg8E0WPLC+mDm2hj/BURuwqmodDnj+y3XSV8Zfu85lZntEl+PQNhiNxQ3tUknqAA9L1DLGbb9j7wXenY9lVe2CwxA1DUTzEGDyt7dRxS6J0qjbhmPZpdMGs4TocYh+0RSqg8v7HrVK7WNhhtjllCeLXiCQJCa/yNrqnx+gddurkIPByl+rPN8hgyinHKtSoPRIyb+CNL9493JiyqqWsuGNr6wLFHm0xI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
